>  3QOS_L
XDIVMTQSPDSLAVSLGERATINXKSSQSVLYSSNNKNYLAWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYXQQYYSTPLT
> Z00023|IGKV4-1*01|Homo sapiens|F|V-REGION|377..681|305 nt|1| | | |101 AA|101+0=101| | | =
.DIVMTQSPDSLAVSLGERATINCKSSQSVLYSSNNKNYLAWYQQKPGQPPKLLIYWASTRESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQQYYSTP..
